#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""create eda_sources table

Revision ID: 86fce48d967f
Revises: fe461863935f
Create Date: 2020-02-22 20:50:20.140754

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '86fce48d967f'
down_revision = 'fe461863935f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eda_sources',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('connection_uri', sa.Text(), nullable=True),
                    sa.Column('source_type', sa.Enum('hdfs', 'database',
                                                     name='edasourcesenum'), nullable=True),
                    sa.Column('tablename', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eda_sources')
    # ### end Alembic commands ###
